#官方Cocoapods的源
source 'https://github.com/CocoaPods/Specs.git'
#长连接Cocoapods的源
source 'https://chcts.iask.in/MSH/ios-repos.git'
platform :ios, 9.0
use_frameworks!
inhibit_all_warnings!

target 'AdForMerchant' do
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'pop'
    pod 'Alamofire', '~> 4.0'
    
    pod 'MBProgressHUD'
    #pod 'CustomIOSAlertView', '~> 0.9.3'
    pod 'MJRefresh', :git=> 'https://github.com/lieonCX/MJRefresh.git'
    pod 'SDWebImage', '~> 4.0'
    pod 'JTCalendar', '~> 2.0'
    pod 'HMSegmentedControl'
    pod 'ObjectMapper', '~> 2.2'
    pod 'SnapKit'
    pod 'SKPhotoBrowser', '~> 4.0'
    pod 'ALCameraViewController',:git=> 'https://github.com/lieonCX/ALCameraViewController.git'
    pod 'MonkeyKing', '~> 1.0'
    pod 'R.swift', '~>3.2.0'
    pod 'CHPushSocket'
    pod 'Whisper'
end
